scala_library(
  name = "{{cookiecutter.project_slug}}-lib",
  srcs = glob(["src/main/scala/**/*.scala"]),
  exports = [
    "@third_party//3rdparty/jvm/com/lihaoyi:pprint",
  ],
  deps = [
    "@third_party//3rdparty/jvm/com/lihaoyi:pprint",
  ]
)
